### ISSUE TITLE
Fix for running on Windows on non-C drive

### ISSUE THREAD

**Issue by yutotakano** [oshikiri/vscode-generic-annotator#91]
Thank you very much for making this extension! I use it for `hledger` on Mac and I love it.

On Windows, the extension unfortunately does not work since it tries to call the command template with `workspaceRoot` = `getWorkspaceFolder(...).uri.path`.
https://github.com/oshikiri/vscode-generic-annotator/blob/f808775d10ebbc1f72269650129e123c623e5976/src/extension.ts#L63 
https://github.com/oshikiri/vscode-generic-annotator/blob/f808775d10ebbc1f72269650129e123c623e5976/src/decoration.ts#L32

I think it should be `...uri.fsPath`.

`uri.path` => `node /g:/Finance/scripts/day-of-week-hints.js /G:/Finance/2023.journal`
-- This causes error because it looks for a folder called `G:` inside `C:`, like `C:/G:/Finance/...`

`uri.fsPath` => `node g:\Finance\scripts\day-of-week-hints.js G:\Finance\2023.journal`
-- I think this should work (not tested)

**Comment by oshikiri** [comment]
>I think it should be ...uri.fsPath.

Agreed
https://code.visualstudio.com/api/references/vscode-api#Uri

**Comment by oshikiri** [comment]
Released as v2.4.0
